### ISSUE TITLE
Python Spefications

### ISSUE THREAD

**Issue by Rotsen0109** [keraattin/EmailAnalyzer#14]
Hello, thanks for your project, it looks very helpful..

I have a issue with it,

What are the things that have to be installed prior to try to execute it ??

I tried with some versions of Python and it did not work

Thanks

**Comment by keraattin** [comment]
Hello @Rotsen0109,

No specific library needed in this version. If any library is needed in the future, I will specify it in the requirements file.

You just need to run the code in **Python 3.X**. 

It is not compatible with **Python 2.X** versions.

Thanks.
